Set consentLanguage without fetch request
InteractiveAdvertisingBureau/iabtcf-es pull request #449
Opened 2024-05-20 14:50 UTC by ccartesonetrust

Calling the changeLanguage method on the GVL class will trigger a new request, resulting in some 404 errors. There are a couple of open tickets related to this issue:

- Cant set consentLanguage with custom GVL #211
- GVL object is being constructed with the gvl json, and setting consentLanguage forces another fetch #405

We propose adding a boolean value to **SKIP** the fetch request.

2024-05-21 13:42 UTC, marco-prontera commented on modules/core/src/GVL.ts
> +          }
I think we could support this directly in the `GVL` constructor by giving the language, perhaps putting the lang as a parameter of an object to be given as a second parameter to the `GVL` constructor. In this way future additions will not cause breaking changes.

My opinion: Imagine calling the `GVL` constructor and then having to call this method with `skipFetchCall` set to `true`, it doesn't seem to fit well. Maybe you might like what I proposed. I hope this thought can help

2024-05-22 21:12 UTC, HeinzBaumann requested changes
I agree with @marco-prontera. Adding a language in the GVL conctructor might be better. 
Also, please add a test case to test.

2024-06-25 15:53 UTC, HeinzBaumann approved these changes
Updates look good to me. @marco-prontera can you also take a quick look at the latest changes? Thanks

2024-07-01 19:27 UTC, 1arrow commented
@marco-prontera can you take a look at the change pushed based on your comment?

2024-07-03 21:16 UTC, marco-prontera approved these changes
LGTM

2024-07-03 21:27 UTC, ccartesonetrust commented
> LGTM

Hi @marco-prontera, do I have to do something else? What is the process for merging this code into the main branch?

2024-07-03 21:29 UTC, HeinzBaumann commented
@lamrowena Can you hit the approve also and merge this. Marco and I reviewed and approved the changes.

2024-07-08 13:56 UTC, lamrowena approved these changes

2024-07-08 14:06 UTC, merged

2024-07-10 12:42 UTC, 1arrow commented
When is the new release planned? we are waiting for this fix.